#!/bin/bash -e
# HFM.net installer for Linux
# Brought to you by The [H]orde
# Copyright (c) 2013
# Dave Corfman <davecorfman@gmail.com>
# Kris Rusocki <kszysiu@gmail.com> 
#

#
# download a file
# syntax: download <URL> [<output-file-name>]
#
download()
{
	local CURL_PARAM

	[ -z "$1" ] && return 1
	if which curl > /dev/null 2>&1 ; then
		[ -z "$2" ] && CURL_PARAM="-O" || CURL_PARAM="-o $2"
		curl -f -s -S -R -L $CURL_PARAM "$1" || return $?
	else
		wget -nv ${2:+-O $2} "$1" || return $?
	fi
	return 0
}

trap "echo Premature exit." ERR

# Make sure we are running with sudo
if [ "$(id -ru)" != "0" ]; then
	echo ERROR: need root privileges. Run with sudo.
	exit 1
fi


if [ -z "$SUDO_USER" ]; then
	echo ERROR: SUDO_USER variable not set, cannot continue.
	exit 1
fi

TARGET=$(eval echo ~$SUDO_USER/Desktop)
if [ ! -e "$TARGET" ]; then
	echo This does not appear to be a GUI install
	exit 1
fi

#
# Make directory for HFM.net, d/l, and unzip
rm -rf /var/lib/hfm
mkdir /var/lib/hfm
cd /var/lib/hfm
download http://hfm-net.googlecode.com/files/HFM%20Any%20CPU%200.9.1.595.zip
unzip "HFM Any CPU 0.9.1.595.zip"
rm -f "HFM Any CPU 0.9.1.595.zip"
download https://raw.github.com/team33/hfminstall/master/hfm_48_48.ico
#
# Get mono
apt-get -qq install libmono-system-runtime4.0-cil libmono-system-runtime-serialization4.0-cil libmono-system-windows-forms4.0-cil libmono-system-data-datasetextensions4.0-cil
#
# download hfm script to /usr/bin
cd /usr/bin
rm -f hfm
download https://raw.github.com/team33/hfminstall/master/hfm
chmod +x hfm
# download desktop icon to $TARGET
cd $TARGET
rm -f HFM.desktop
download https://raw.github.com/team33/hfminstall/master/HFM.desktop
chmod +x HFM.desktop
